FROM seancheung/dockerwine:wine
LABEL maintainer="Sean Cheung <theoxuanx@gmail.com>"

RUN set -ex && \
    echo "Installing dependencies..." && \
    apk add --no-cache --allow-untrusted tigervnc && \
    echo "Clean Up..." && \
    rm -rf /var/cache/apk/*

COPY tigervnc.conf /etc/supervisor/conf.d/

EXPOSE 5900