FROM seancheung/dockerwine:wine
LABEL maintainer="Sean Cheung <theoxuanx@gmail.com>"

RUN set -ex && \
    echo "Installing dependencies..." && \
    apk add --no-cache --allow-untrusted xvfb x11vnc && \
    echo "Clean Up..." && \
    rm -rf /var/cache/apk/*

COPY x11vnc.conf /etc/supervisor/conf.d/
COPY x11.entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]