name: Build TigerVNC Image

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["Dockerfile.tigervnc", "tigervnc.conf", "tigervnc.entrypoint.sh"]

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.tigervnc
          push: true
          tags: seancheung/dockerwine:tigervnc